#!/usr/bin/env node
/** Generate Dart protocol types from schemas/protocol/v1.json */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "../..");
const schema = JSON.parse(
  readFileSync(join(root, "schemas/protocol/v1.json"), "utf8"),
);
const outDir = join(root, "apps/desktop/lib/src/generated");
mkdirSync(outDir, { recursive: true });
const outPath = join(outDir, "protocol_v1.dart");

const methods = Object.values(schema.methodCatalog).flat();

const contents = `// GENERATED by scripts/protocol/generate-dart.mjs — do not edit.

/// Retcon local protocol v1 wire types.
library;

class ProtocolV1 {
  static const int version = 1;
  static const List<String> methods = [
${methods.map((method) => `    '${method}',`).join("\n")}
  ];
}

class Discovery {
  const Discovery({
    required this.transport,
    required this.path,
    required this.token,
    required this.pid,
    required this.version,
    required this.protocolVersion,
  });

  factory Discovery.fromJson(Map<String, dynamic> json) => Discovery(
    transport: json['transport'] as String,
    path: json['path'] as String,
    token: json['token'] as String,
    pid: json['pid'] as int,
    version: json['version'] as String,
    protocolVersion: json['protocolVersion'] as int,
  );

  final String transport;
  final String path;
  final String token;
  final int pid;
  final String version;
  final int protocolVersion;
}

class ClientHello {
  const ClientHello({
    required this.clientVersion,
    this.features = const [],
  });

  Map<String, dynamic> toJson() => {
    'kind': 'client.hello',
    'protocolVersion': ProtocolV1.version,
    'clientVersion': clientVersion,
    'features': features,
  };

  final String clientVersion;
  final List<String> features;
}

class RpcRequest {
  const RpcRequest({
    required this.id,
    required this.method,
    this.params = const {},
  });

  Map<String, dynamic> toJson() => {
    'id': id,
    'method': method,
    'params': params,
  };

  final int id;
  final String method;
  final Map<String, dynamic> params;
}

class PingFrame {
  const PingFrame();

  Map<String, dynamic> toJson() => const {'kind': 'ping'};
}

class CancelFrame {
  const CancelFrame(this.id);

  Map<String, dynamic> toJson() => {'kind': 'request.cancel', 'id': id};

  final int id;
}
`;

writeFileSync(outPath, contents);
console.log(`wrote ${outPath}`);
